# Generated by Django 4.2.1 on 2026-08-20 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('legislative', 'Legislative')], default='technical', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(help_text='e.g., ADT E# PIN 3 (5 Days)', max_length=200)),
                ('venue_info', models.CharField(help_text='e.g., JetPark', max_length=100)),
                ('capacity', models.PositiveIntegerField(default=12, help_text='Total seats available')),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('legislative', 'Legislative')], default='technical', max_length=20)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='system.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_range', models.CharField(blank=True, max_length=100, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('bell_branch', models.CharField(blank=True, max_length=150)),
                ('surname', models.CharField(default='', max_length=100)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('company_number', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(default='technical', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_booking', to='system.scheduleslot')),
            ],
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='system.trainingweek'),
        ),
        migrations.CreateModel(
            name='LegislativeBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('surname', models.CharField(default='', max_length=100)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('company_number', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(default='legislative', max_length=20)),
                ('id_pdf', models.FileField(blank=True, null=True, upload_to='booking/legislative/ids')),
                ('education_pdf', models.FileField(blank=True, null=True, upload_to='booking/legislative/education')),
                ('medical_pdf', models.FileField(blank=True, null=True, upload_to='booking/legislative/medical')),
                ('drivers_license_pdf', models.FileField(blank=True, null=True, upload_to='booking/legislative/drivers_license')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislative_booking', to='system.scheduleslot')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='scheduleslot',
            unique_together={('instructor', 'week')},
        ),
    ]
