# Generated by Django 4.2.1 on 2026-08-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingbooking',
            name='bell_branch',
        ),
        migrations.RemoveField(
            model_name='trainingbooking',
            name='email',
        ),
        migrations.AddField(
            model_name='trainingbooking',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='trainingbooking',
            name='email_admin',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trainingbooking',
            name='email_candidate',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='LegislativeScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(help_text='e.g., ADT E# PIN 3 (5 Days)', max_length=200)),
                ('venue_info', models.CharField(help_text='e.g., JetPark', max_length=100)),
                ('capacity', models.PositiveIntegerField(default=12, help_text='Total seats available')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislative_slots', to='system.instructor')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislative_slots', to='system.trainingweek')),
            ],
            options={
                'verbose_name': 'Legislative Schedule Slot',
                'verbose_name_plural': 'Legislative Schedule Slots',
            },
        ),
    ]
