# Generated by Django 4.2.1 on 2026-08-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_trainingbooking_bell_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleslot',
            name='category',
        ),
        migrations.AlterField(
            model_name='legislativebooking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislative_booking', to='system.legislativescheduleslot'),
        ),
    ]
