# Generated by Django 4.2.1 on 2026-08-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_scheduleslot_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislativebooking',
            name='email',
        ),
        migrations.AddField(
            model_name='legislativebooking',
            name='email_admin',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='legislativebooking',
            name='email_candidate',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
