# Generated by Django 4.2.1 on 2026-08-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_legislativebooking_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislativebooking',
            name='previous_license_pdf',
            field=models.FileField(blank=True, null=True, upload_to='booking/legislative/previous_license'),
        ),
    ]
