# Generated by Django 4.2.1 on 2026-08-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_legislativebooking_previous_license_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorTrainingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email_company', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('surname', models.CharField(default='', max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('course', models.CharField(blank=True, max_length=150)),
                ('course_name', models.CharField(blank=True, max_length=150)),
                ('number_of_deligates', models.IntegerField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
