# Generated by Django 4.2.1 on 2026-08-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_operatortrainingbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatortrainingbooking',
            name='number_of_deligates',
            field=models.IntegerField(blank=True),
        ),
    ]
