# Generated by Django 4.2.1 on 2026-08-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_operatortrainingbooking_number_of_deligates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatortrainingbooking',
            old_name='course',
            new_name='course_type',
        ),
    ]
