# Generated by Django 4.2.1 on 2026-08-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_rename_course_operatortrainingbooking_course_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatortrainingbooking',
            old_name='email_company',
            new_name='company_email',
        ),
    ]
