# Generated by Django 4.2.1 on 2026-08-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_rename_email_company_operatortrainingbooking_company_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatortrainingbooking',
            old_name='area',
            new_name='location_name',
        ),
    ]
