# Generated by Django 4.2.1 on 2026-08-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_rename_area_operatortrainingbooking_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingbooking',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
