# Generated by Django 4.2.1 on 2026-08-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_trainingbooking_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingbooking',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
