# Generated by Django 4.2.1 on 2026-08-28 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_trainingbooking_is_declined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingbooking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_booking', to='system.scheduleslot'),
        ),
    ]
