# Generated by Django 4.2.1 on 2026-08-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_alter_trainingbooking_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingbooking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
