# Generated by Django 5.2.17 on 2026-08-28 09:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_historicaltrainingbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='legislativebooking',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legislativebooking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legislativebooking',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='legislativebooking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legislative_booking', to='system.legislativescheduleslot'),
        ),
        migrations.CreateModel(
            name='HistoricalLegislativeBooking',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email_admin', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_candidate', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('surname', models.CharField(default='', max_length=100)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('company_number', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(default='legislative', max_length=20)),
                ('id_pdf', models.TextField(blank=True, max_length=100, null=True)),
                ('education_pdf', models.TextField(blank=True, max_length=100, null=True)),
                ('medical_pdf', models.TextField(blank=True, max_length=100, null=True)),
                ('drivers_license_pdf', models.TextField(blank=True, max_length=100, null=True)),
                ('previous_license_pdf', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_declined', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='system.legislativescheduleslot')),
            ],
            options={
                'verbose_name': 'historical legislative booking',
                'verbose_name_plural': 'historical legislative bookings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
