# Generated by Django 5.2.17 on 2026-08-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_legislativebooking_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatortrainingbooking',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
