# Generated by Django 5.2.17 on 2026-08-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_operatortrainingbooking_is_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatortrainingbooking',
            old_name='company_email',
            new_name='admin_email',
        ),
        migrations.RemoveField(
            model_name='operatortrainingbooking',
            name='company_name',
        ),
    ]
