# Generated by Django 5.2.17 on 2026-08-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_rename_company_email_operatortrainingbooking_admin_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallegislativebooking',
            old_name='email_admin',
            new_name='admin_email',
        ),
        migrations.RenameField(
            model_name='historicallegislativebooking',
            old_name='email_candidate',
            new_name='candidate_email',
        ),
        migrations.RenameField(
            model_name='legislativebooking',
            old_name='email_admin',
            new_name='admin_email',
        ),
        migrations.RenameField(
            model_name='legislativebooking',
            old_name='email_candidate',
            new_name='candidate_email',
        ),
    ]
