# Generated by Django 5.2.17 on 2026-08-31 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_rename_email_admin_historicallegislativebooking_admin_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltrainingbooking',
            old_name='email_admin',
            new_name='admin_email',
        ),
        migrations.RenameField(
            model_name='historicaltrainingbooking',
            old_name='email_candidate',
            new_name='candidate_email',
        ),
        migrations.RenameField(
            model_name='trainingbooking',
            old_name='email_admin',
            new_name='admin_email',
        ),
        migrations.RenameField(
            model_name='trainingbooking',
            old_name='email_candidate',
            new_name='candidate_email',
        ),
    ]
