# Generated by Django 5.2.17 on 2026-08-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_rename_email_admin_historicaltrainingbooking_admin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatortrainingbooking',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
