# Generated by Django 5.2.17 on 2026-09-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_scheduleslot_prerequisite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltrainingbooking',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltrainingbooking',
            name='slot',
        ),
        migrations.DeleteModel(
            name='HistoricalLegislativeBooking',
        ),
        migrations.DeleteModel(
            name='HistoricalTrainingBooking',
        ),
    ]
