# Generated by Django 5.2.17 on 2026-09-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_remove_historicaltrainingbooking_history_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legislativebooking',
            old_name='candidate_email',
            new_name='supervisor_email',
        ),
    ]
