# Generated by Django 5.2.17 on 2026-09-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_rename_candidate_email_legislativebooking_supervisor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatortrainingbooking',
            old_name='course_name',
            new_name='machine_name',
        ),
    ]
